insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (26, 'Engrenagem', 'Cobre', 2.44, 'kg', 2.62, 'mm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (49, 'Válvula de controle', 'Ferro fundido', 2.69, 'g', 4.83, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (27, 'Tubulação de condução', 'Alumínio', 2.08, 'g', 6.31, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (18, 'Rotor', 'Ferro fundido', 3.17, 'g', 4.8, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (26, 'Estator', 'Aço', 2.77, 'Ton', 1.74, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (51, 'Placa de circuito', 'Alumínio', 1.35, 'g', 1.92, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (78, 'Rolamento', 'Aço', 1.37, 'g', 3.18, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (64, 'Filtro', 'Cobre', 2.13, 'kg', 2.98, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (32, 'Cilindro hidráulico', 'Ferro fundido', 1.68, 'g', 2.11, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (76, 'Eixo', 'Alumínio', 1.61, 'Ton', 1.66, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (63, 'Bobina', 'Ferro fundido', 4.0, 'Ton', 3.29, 'mm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (41, 'Conector elétrico', 'Alumínio', 3.0, 'kg', 4.94, 'mm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (60, 'Termopar', 'Ferro fundido', 2.78, 'g', 7.46, 'mm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (95, 'Sensor de pressão', 'Aço', 3.4, 'kg', 1.06, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (61, 'Ventilador', 'Cobre', 1.75, 'Ton', 6.22, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (44, 'Roldana', 'Ferro fundido', 2.85, 'kg', 5.86, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (18, 'Acoplamento', 'Ferro fundido', 3.84, 'g', 6.12, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (74, 'Trocador de calor', 'Cobre', 3.31, 'kg', 2.59, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (54, 'Manômetro', 'Alumínio', 2.79, 'kg', 7.34, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (98, 'Filtro de ar', 'Cobre', 3.82, 'g', 7.97, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (25, 'Placa de base', 'Ferro fundido', 3.67, 'Ton', 7.38, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (89, 'Elemento de aquecimento', 'Aço', 3.08, 'Ton', 7.79, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (100, 'Hélice', 'Cobre', 2.24, 'kg', 7.78, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (54, 'Pistão', 'Cobre', 3.14, 'g', 6.23, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (90, 'Sonda de temperatura', 'Ferro fundido', 2.14, 'g', 4.8, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (51, 'Válvula solenoide', 'Aço', 2.76, 'Ton', 3.63, 'mm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (44, 'Câmara de combustão', 'Alumínio', 2.36, 'kg', 3.66, 'mm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (11, 'Rolo transportador', 'Aço', 1.58, 'Ton', 7.26, 'mm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (94, 'Contator', 'Alumínio', 1.29, 'kg', 3.74, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (93, 'Transmissão', 'Aço', 1.84, 'Ton', 3.16, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (87, 'Disjuntor', 'Ferro fundido', 2.36, 'Ton', 7.33, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (29, 'Tubo de refrigeração', 'Aço', 1.81, 'kg', 4.35, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (63, 'Isolador', 'Aço', 2.6, 'kg', 1.55, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (75, 'Mangueira flexível', 'Aço', 3.68, 'g', 7.96, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (53, 'Selo mecânico', 'Alumínio', 3.79, 'kg', 7.32, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (49, 'Módulo de controle', 'Alumínio', 3.56, 'Ton', 3.89, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (23, 'Resistor', 'Aço', 1.94, 'g', 7.42, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (19, 'Placa de identificação', 'Cobre', 2.64, 'g', 4.6, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (38, 'Motor elétrico', 'Aço', 1.83, 'g', 3.97, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (23, 'Acumulador de pressão', 'Ferro fundido', 1.09, 'Ton', 4.6, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (88, 'Rolamento de esferas', 'Aço', 3.94, 'Ton', 1.37, 'mm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (94, 'Barramento', 'Alumínio', 2.44, 'Ton', 6.49, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (62, 'Gerador de energia', 'Cobre', 2.61, 'kg', 6.12, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (25, 'Sistema de exaustão', 'Cobre', 1.56, 'Ton', 2.72, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (96, 'Rampa de acesso', 'Aço', 1.03, 'g', 4.18, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (55, 'Atuador', 'Aço', 3.55, 'kg', 7.88, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (90, 'Cinta transportadora', 'Aço', 3.9, 'Ton', 3.51, 'mm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (23, 'Gerador de vapor', 'Aço', 1.38, 'Ton', 5.42, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (50, 'Elemento filtrante', 'Ferro fundido', 1.57, 'Ton', 1.08, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (14, 'Flange', 'Aço', 1.04, 'Ton', 1.18, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (71, 'Unidade de controle', 'Ferro fundido', 3.13, 'kg', 7.98, 'mm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (34, 'Válvula de segurança', 'Ferro fundido', 1.58, 'Ton', 5.13, 'mm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (55, 'Conector rápido', 'Ferro fundido', 1.1, 'g', 3.45, 'mm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (23, 'Duto de ventilação', 'Cobre', 3.43, 'g', 7.1, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (33, 'Grade de proteção', 'Alumínio', 3.3, 'g', 7.63, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (59, 'Acionador', 'Cobre', 2.29, 'Ton', 1.76, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (40, 'Reservatório de óleo', 'Ferro fundido', 2.88, 'g', 7.5, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (52, 'Conjunto de molas', 'Cobre', 2.35, 'kg', 1.63, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (95, 'Cabeçote', 'Ferro fundido', 3.34, 'Ton', 5.89, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (98, 'Chave de fenda', 'Cobre', 1.12, 'kg', 2.62, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (19, 'Viga de suporte', 'Ferro fundido', 2.62, 'g', 6.31, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (77, 'Câmara de resfriamento', 'Ferro fundido', 3.18, 'g', 2.81, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (61, 'Transformador', 'Cobre', 1.69, 'Ton', 4.02, 'mm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (79, 'Interruptor de pressão', 'Cobre', 3.43, 'g', 5.66, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (19, 'Parafuso de fixação', 'Aço', 1.66, 'g', 3.0, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (84, 'Filtro de óleo', 'Cobre', 2.66, 'kg', 6.01, 'mm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (13, 'Régua de medição', 'Cobre', 1.06, 'g', 7.3, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (89, 'Correia transportadora', 'Alumínio', 3.87, 'kg', 6.89, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (14, 'Elemento sensor', 'Cobre', 3.61, 'Ton', 7.02, 'mm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (70, 'Tubo de escape', 'Aço', 2.68, 'g', 2.87, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (95, 'Rolo de suporte', 'Alumínio', 1.94, 'kg', 5.5, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (88, 'Dispositivo de bloqueio', 'Alumínio', 2.85, 'g', 4.02, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (29, 'Grade de ventilação', 'Cobre', 1.1, 'kg', 4.08, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (48, 'Elemento de filtragem', 'Alumínio', 2.28, 'kg', 7.96, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (20, 'Junta de expansão', 'Alumínio', 3.09, 'g', 4.78, 'mm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (96, 'Válvula de alívio', 'Cobre', 3.92, 'g', 6.3, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (17, 'Haste de conexão', 'Cobre', 1.36, 'Ton', 4.05, 'mm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (96, 'Dispositivo de segurança', 'Cobre', 3.87, 'Ton', 5.19, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (52, 'Válvula de retenção', 'Cobre', 2.85, 'g', 3.39, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (24, 'Suporte de montagem', 'Alumínio', 2.09, 'Ton', 2.35, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (76, 'Manifold', 'Alumínio', 1.93, 'Ton', 5.0, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (14, 'Cabo de ligação', 'Alumínio', 1.92, 'kg', 6.61, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (50, 'Módulo de energia', 'Ferro fundido', 3.16, 'g', 7.42, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (67, 'Resfriador de ar', 'Alumínio', 1.87, 'Ton', 1.86, 'mm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (77, 'Rotor de turbina', 'Cobre', 2.27, 'Ton', 3.57, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (82, 'Mola de compressão', 'Aço', 3.81, 'g', 7.97, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (90, 'Bocal de descarga', 'Cobre', 3.75, 'g', 4.43, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (56, 'Sensor de fluxo', 'Alumínio', 1.91, 'g', 1.98, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (90, 'Radiador', 'Aço', 1.1, 'g', 6.98, 'mm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (91, 'Mangote flexível', 'Cobre', 3.61, 'Ton', 2.55, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (99, 'Unidade de resfriamento', 'Ferro fundido', 2.68, 'Ton', 5.68, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (42, 'Suporte de fixação', 'Cobre', 2.31, 'g', 2.73, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (90, 'Chave inglesa', 'Aço', 1.11, 'Ton', 1.67, 'pol');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (55, 'Válvula de bloqueio', 'Aço', 3.62, 'g', 6.26, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (62, 'Eletrodo', 'Aço', 3.92, 'g', 4.18, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (88, 'Bico de pulverização', 'Ferro fundido', 1.68, 'g', 7.18, 'cm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (58, 'Placa de proteção', 'Ferro fundido', 1.76, 'Ton', 4.09, 'mm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (46, 'Caldeira', 'Cobre', 1.18, 'kg', 6.1, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (30, 'Válvula de regulagem', 'Cobre', 2.89, 'g', 6.37, 'm');
insert into pecas (pk_idPeca, descricao, material, pesoNum, pesoUnidade, dimensaoNum, dimensaoUnidade) values (61, 'Rolo de pressão', 'Aço', 1.35, 'Ton', 2.27, 'cm');